# Generated by Django 3.2.9 on 2023-11-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farms', '0002_auto_20231007_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmdata',
            name='nitrogen',
        ),
        migrations.RemoveField(
            model_name='farmdata',
            name='phosphorous',
        ),
        migrations.RemoveField(
            model_name='farmdata',
            name='potassium',
        ),
        migrations.AlterField(
            model_name='farmdata',
            name='humidity',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmdata',
            name='moisture',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmdata',
            name='temperature',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
