# Generated by Django 3.2.9 on 2023-11-15 09:19

import ckeditor.fields
from django.db import migrations, models
import recommendations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('date', models.DateTimeField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('images', models.ImageField(blank=True, upload_to=recommendations.models.upload_to_images)),
            ],
        ),
    ]
